### ISSUE TITLE
[Bug]: Example docker-compose.yml not working anymore

### ISSUE THREAD

**Issue by ckagerer** [ocrmypdf/OCRmyPDF#1415]
#### Error description

Use OCRmyPDF in batch mode to automatically convert all files in a directory. Setup corresponds to that in https://github.com/ocrmypdf/OCRmyPDF/blob/d303b42c8610d3bec0be19b089008ece821cbe9e/misc/docker-compose.example.yml.
Since updating to v16.6.0, however, this no longer works, as the path in which “watcher.py” can be found has apparently changed (unintentionally).

#### Solution / Workaround

Change ...

```
# SPDX-FileCopyrightText: 2022 James R. Barlow
# SPDX-License-Identifier: MIT
---
version: "3.3"
services:
  ocrmypdf:
    restart: always
    container_name: ocrmypdf
    image: jbarlow83/ocrmypdf
    volumes:
      - "/media/scan:/input"
      - "/mnt/scan:/output"
    environment:
      - OCR_OUTPUT_DIRECTORY_YEAR_MONTH=0
    user: "<SET TO YOUR USER ID>:<SET TO YOUR GROUP ID>"
    entrypoint: python3
    command: watcher.py
```

... to

```
# SPDX-FileCopyrightText: 2022 James R. Barlow
# SPDX-License-Identifier: MIT
---
version: "3.3"
services:
  ocrmypdf:
    restart: always
    container_name: ocrmypdf
    image: jbarlow83/ocrmypdf
    volumes:
      - "/media/scan:/input"
      - "/mnt/scan:/output"
    environment:
      - OCR_OUTPUT_DIRECTORY_YEAR_MONTH=0
    user: "<SET TO YOUR USER ID>:<SET TO YOUR GROUP ID>"
    entrypoint: python3
    command: misc/watcher.py
```

### Where are you installing/running from?

Docker container

### OCRmyPDF version

16.6.0

### What operating system are you working on?

Linux

### Simple sanity checks

- [X] Operating system is currently supported by its vendor (not end of life)
- [X] Python version is compatible with OCRmyPDF
- [X] This issue is not about a specific input file

### Relevant log output

```plain text
ocrmypdf    | python3: can't open file '/app/watcher.py': [Errno 2] No such file or directory
```
